require "rails_helper"

RSpec.describe "whiteboard controller syntax" do
  it "keeps pointer drawing, fullscreen collapse and autosave wired" do
    source = Rails.root.join("app/javascript/controllers/whiteboard_controller.js").read
    stylesheet = Rails.root.join("app/assets/stylesheets/application.css").read

    expect(source).to include("this.canvasContext = this.canvasTarget.getContext(\"2d\")")
    expect(source).not_to include("this.context = this.canvasTarget.getContext")
    expect(source).to include("this.state = this.normalizedState(this.element.notaeWhiteboardState || this.initialJsonValue || {})")
    expect(source).to include('static targets = [ "canvas", "status", "toolButton", "colorInput", "diameterInput", "diameterValue", "openButton", "collapseButton" ]')
    expect(source).to include("this.fullscreenPlaceholder = this.element.notaeWhiteboardPlaceholder || null")
    expect(source).to include('this.canvasTarget.addEventListener("pointerdown", this.pointerDownHandler)')
    expect(source).to include('this.canvasTarget.addEventListener("pointermove", this.pointerMoveHandler)')
    expect(source).to include('this.canvasTarget.addEventListener("pointerrawupdate", this.pointerMoveHandler)')
    expect(source).to include('this.canvasTarget.addEventListener("pointerup", this.pointerUpHandler)')
    expect(source).to include('this.canvasTarget.addEventListener("contextmenu", this.suppressSelectionHandler)')
    expect(source).to include('this.canvasTarget.addEventListener("selectstart", this.suppressSelectionHandler)')
    expect(source).to include('this.canvasTarget.addEventListener("dragstart", this.suppressSelectionHandler)')
    expect(source).to include('this.canvasTarget.removeEventListener("pointerrawupdate", this.pointerMoveHandler)')
    expect(source).to include('this.canvasTarget.removeEventListener("contextmenu", this.suppressSelectionHandler)')
    expect(source).to include('this.canvasTarget.removeEventListener("selectstart", this.suppressSelectionHandler)')
    expect(source).to include('this.canvasTarget.removeEventListener("dragstart", this.suppressSelectionHandler)')
    expect(source).to include("pointerEventsFor(event)")
    expect(source).to include("suppressSelection(event)")
    expect(source).to include("this.clearSelection()")
    expect(source).to include("window.getSelection?.()?.removeAllRanges?.()")
    expect(source).to include("const coalescedEvents = event.getCoalescedEvents?.() || []")
    expect(source).to include("pointerEvents.push(event)")
    expect(source).not_to include("getPredictedEvents")
    expect(source).not_to include("pointerEvents.push(...predictedEvents)")
    expect(source.scan("this.pointerEventsFor(event)").length).to be >= 2
    expect(source).to include("this.strokeRevision = 0")
    expect(source).to include("markStrokeChanged()")
    expect(source).to include("this.strokeRevision += 1")
    expect(source).to include("this.persistElementState()")
    expect(source).to include("persistElementState({ updateAttribute = false } = {})")
    expect(source).to include("this.element.notaeWhiteboardState = content")
    expect(source).to include("this.element.dataset.whiteboardInitialJsonValue = JSON.stringify(content)")
    expect(source).to include("const saveRevision = this.strokeRevision")
    expect(source).to include("if (saveRevision !== this.strokeRevision)")
    expect(source).to include("this.queueSave()")
    expect(source).to include("queueCanvasResize(callback)")
    expect(source).to include("if (this.fullscreenActive()) this.queueCanvasResize()")
    expect(source).to include('this.canvasTarget.style.removeProperty("width")')
    expect(source).to include('this.canvasTarget.style.removeProperty("height")')
    expect(source).not_to include('this.canvasTarget.style.width = `${width}px`')
    expect(source).not_to include('this.canvasTarget.style.height = `${height}px`')
    expect(source).to include("this.drawStrokeSegment(this.activeStroke, previous, point)")
    expect(source).to include("if (previous.x === point.x && previous.y === point.y) return")
    expect(source).not_to include("MIN_POINT_DISTANCE")
    expect(source).to include("applyStrokeStyle(context, stroke)")
    expect(source).to include("drawInkLayer(context, width, height)")
    expect(source).to include('context.globalCompositeOperation = "destination-out"')
    expect(source).to include('[ "pencil", "marker", "eraser" ].includes(stroke.tool)')
    expect(source).not_to include("this.strokes = this.strokes.filter")
    expect(source).to include("context.shadowBlur = Math.max")
    expect(source).to include('this.element.classList.add("is-fullscreen")')
    expect(source).to include("this.rememberInlinePosition()")
    expect(source).to include("this.element.notaeWhiteboardReturnParent = this.element.parentNode")
    expect(source).to include("document.body.appendChild(this.element)")
    expect(source).to include("this.element.notaeWhiteboardPortaling = true")
    expect(source).to include("updateDocumentFullscreenState(isFullscreen)")
    expect(source).to include("this.animateFromRect(inlineRect, fullscreenRect)")
    expect(source).to include("this.canvasTarget.focus({ preventScroll: true })")
    exit_fullscreen = source[/exitFullscreen\(event\) \{.*?\n  \}/m]
    expect(exit_fullscreen.index("this.persistElementState()")).to be < exit_fullscreen.index("this.restoreInlinePosition()")
    save_method = source[/async save\(\) \{.*?\n  \}/m]
    expect(save_method.index("this.persistElementState({ updateAttribute: true })")).to be > save_method.index("this.board = this.state.board")
    expect(source).to include("this.restoreInlinePosition()")
    expect(source).to include("returnParent.insertBefore(this.element, this.fullscreenPlaceholder || null)")
    expect(source).to include('this.element.classList.remove("is-fullscreen")')
    expect(source).to include("this.animateFromRect(fullscreenRect, inlineRect)")
    expect(source).to include("this.fullscreenAnimation.finished.then(() => this.resizeCanvas()).catch(() => {})")
    expect(source).to include("updateFullscreenControls()")
    expect(source).to include("event?.stopPropagation()")
    expect(source).to include('selectCustomColor(event)')
    expect(source).to include("selectDiameter(event)")
    expect(source).to include("MIN_DIAMETER")
    expect(source).to include("MAX_DIAMETER")
    expect(source).to include('this.element.style.setProperty("--notae-whiteboard-active-color", color)')
    expect(source).to include("this.colorInputTarget.value = color")
    expect(source).to include('this.element.style.setProperty("--notae-whiteboard-diameter-progress", `${progress}%`)')
    expect(source).to include('this.diameterValueTarget.textContent = `${this.diameter}px`')
    expect(source).to include('if (!this.fullscreenActive())')
    expect(source).to include('JSON.stringify({ block: { content_json: content } })')
    expect(source).to include('delete content.whiteboard_autofocus')
    expect(stylesheet).to include(".notae-doc-block.is-type-whiteboard > .notae-whiteboard:not(.is-fullscreen) {\n  margin-top: 0.7rem;\n}")
    expect(stylesheet).to include(".notae-whiteboard:not(.is-fullscreen) .notae-whiteboard-titlebar {\n  padding-right: 2.6rem;\n}")
    expect(stylesheet).to include(".notae-whiteboard:not(.is-fullscreen) .notae-whiteboard-toolbar {\n  display: none;\n}")
    expect(stylesheet).to include(".notae-whiteboard [hidden] {\n  display: none !important;\n}")
    expect(stylesheet).to include("-webkit-touch-callout: none;")
    expect(stylesheet).to include("-webkit-user-select: none;")
    expect(stylesheet).to include("user-select: none;")
    expect(stylesheet).to include("writing-mode: vertical-lr;")
  end
end
